name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.3"

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install ABIGen
        run: |
          go install github.com/ethereum/go-ethereum/cmd/abigen@v1.13.5

      - uses: actions/setup-node@v4
        with:
          node-version: "22.3.0"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm run lint

      - name: Check formatting
        run: forge fmt --check
