name: Foundry

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check contract sizes
        run: forge build --sizes --deny-warnings

      - name: Tests
        run: forge test

      - name: Save compiled contracts and ABIs
        run: |
          mkdir -p artifacts
          cp -r out/Dispatcher.sol/Dispatcher.json artifacts/
          cp -r out/UniversalChannelHandler.sol/UniversalChannelHandler.json artifacts/
          cp -r out/Mars.sol/Mars.json artifacts/
          cp -r out/Earth.sol/Earth.json artifacts/
          cp -r out/Moon.sol/Moon.json artifacts/
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-contracts
          path: artifacts

  release:
    runs-on: ubuntu-latest
    needs: test
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: compiled-contracts
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/**
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}
