name: Foundry

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check contract sizes
        run: forge build --sizes --deny-warnings

      - name: Tests
        run: forge test

      - name: Save compiled contracts and ABIs
        run: |
          mkdir -p artifacts
          cp -r out/* artifacts/
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-contracts
          path: artifacts

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: compiled-contracts
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
